spell-checking:
  stage: readme_cspell_and_cppcheck
  tags:
    - aurora_psdk_runner
  script:
    - sudo cp ./gitlab-ci/project-words.txt /home/gitlab-runner/cspell 
    - /home/gitlab-runner/.nvm/versions/node/v22.14.0/bin/npx cspell --config /home/gitlab-runner/cspell/cspell.json "./README.md" "./README.ru.md" --show-suggestions